api:
    resource: "@ApiBundle/Controller/"
    prefix:   /api

core:
    resource: "@CoreBundle/Controller/"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

routing_rest:
    resource: routing_rest.yml
