services:
    api_request_listner:
            class: ApiBundle\Listener\ApiRequestListener
            tags:
                - { name: kernel.event_listener, event: kernel.terminate, method: onControllerResponse }
